# Presentation for Promise , Arrow Function , Async await OF ES6


## Table of content 
 + [Promise](#promise)
 + [Arrow Function](#arrow-function)
 + [Async await](#async-await)



## Promise 
 ### Promise là gì  ? 
  >  Promise sinh ra để xử lý các câu lệnh bất đồng bộ 

  ### Đầu tiên thì mình nói đến đồng bộ or bất đồng bộ trong js 

  ### Đồng bộ 
  ```
  console.log(1)
  console.log(2)
  console.log(3)

  output :  1 2 3  
  // nó sẽ chạy lần lượt từ trên xuống dưới 
  ```

  ### Bất đồng bộ 
  ```
  setTimeout(()=>console.log(1))
  console.log(2)
  console.log(3)
  
  output : 2 3 1
  // nó sẽ không đợi dòng 1 , mà nó sẽ thực hiện đồng thời 2 3  , dòng 1 sẽ được ném vào web api để đếm , khi nào xong sẽ được đẩy xuống callback queue , rồi đưa lên lại call stack 
  ```
  
  > Vậy làm sao tôi muốn chạy xong dòng 1 thì dòng 2 chạy , dòng 3 chạy sau dòng 2 thì ban đầu sinh ra khái niệm callback

  ##   Callback là gì ?
  > Callback hay được gọi là call me later , nghĩa là thực hiện xong task chính rồi thì hàm này được gọi thì cái đó gọi là callback , hay nói cách khác , 1 hàm là tham số của 1 function khác , được gọi sau khi function đó chạy thì được gọi là callback 

  Example :
  Bây giờ mình có yêu cầu như sau  :  Công việc 1 chạy xong nhả data cho công việc 2 xử lý 
  ```
  function function1(callback){
 // xong công việc 1 thì gọi callback 
 setTimeout(function(){
 console.log("Hoàn thành công việc 1")
 callback("data từ function 1 \n")

 },1000)
}

function function2(data, callback){
    setTimeout(function(){
        console.log("Hoàn thành công việc 2")
        callback("data từ function 2 \n")
       
        },1000)

}

/*
Phân tích  :  Công việc 1 mất 1s , sau 1s thì nó gọi callback  , Công việc 2 nhận vào data, sau khi công việc 2 xong thì là gọi callback , đấy là xong đoạn declare
*/

function1((data) => {
    function2(data,(data) =>{
        console.log(data)
    })
})

/*
 Call :
 Nhìn vào function1 , nó sẽ nhận 1 function để sau khi xong việc thì nó call đến
*/
function1(function2) 
// sau khi xong việc thì nó sẽ gọi đến function2 => thỏa mãn yêu cầu nhưng mà ko được truyền kiểu này , bởi vì mình sẽ không truyền được data từ func1 cho function2 , vậy ở đâu chúng ta cần 1 bước trung gian là 1 hàm lấy data từ function1 rồi đẩy vào function2 

```
![alt text](image.png)

```
output : 
Hoàn thành công việc 1 
Hoàn thành công việc 2 
Hoàn thành công việc 3 
// lưu ý việc truyền : thì chỉ truyền anynomous function 
```
Nếu số lượng công việc sinh lên khoảng 10 => thì nó sinh ra một cái gọi là callback hell 

![alt text](image-1.png)

Để xử lý vấn đề này thì sinh ra Promise 

### Promise là gì ? 
Cơ bản nó chỉ là một object thể hiện trạng thái của một sự kiện bất đồng bộ , thành công hay thất bại 

cơ bản nó có 3 trạng thái như hình :

![alt text](image-2.png)

Giống như callback , xong việc này mình mới xử lý việc kia  , thì promise cơ chế tương tự , nếu reslove thì mình xử lí một việc , hoặc nếu reject thì mình xử lí một việc nào đó 

Example: Xong việc 1 thì ta mới xử lý việc 2 
```
const promise1 = new Promise((reslove, reject)=>{
    setTimeout(()=>{
      console.log("Hoàn thành việc 1")
      reslove("data từ việc 1");

    },1000) 
   
})

promise1.then((data)=>{
   return new Promise((reslove,reject)=>{
    console.log("Hoàn thành việc 2")
    reslove("data từ việc 2");

      
   })
})
.then((data)=>{
  console.log("đã hoàn thành 2 việc");

})

output : 
Hoàn thành việc 1 
Hoàn thành việc 2 
đã hoành thành 2 việc 

/*
.then : khi reslove 
.catch : khi reject 
cả hai vẫn nhận vào 1 callback để thực hiện 
*/
```

## Async await 
là bản nâng cấp ES7 , giúp viết code bất đồng bộ trong giống đồng bộ hơn , dễ nhìn hơn
Async keyword :  thông báo là rằng function này là hàm xử lí bất đồng bộ , nó sẽ trả về 1 promise được reslove với việc return bất cứ việc gì 
```
async function myFunction() {
    return "Hello";
  }
 

  myFunction().then((data) => console.log(data))

  //output :  Hello 
  Như trên là function myFunction return Promise.reslove("Hello"), nên ta dùng then để lấy dữ liệu trả về.
```
await keyword :  là keyword đứng trước các promise , nó được sử dụng trong hàm async , nó sẽ bắt hàm async đợi đến khi promise trả về value , nếu có lỗi thì kết hợp thêm try/catch để bắt lỗi 
sử dụng await trong một hàm async, nó sẽ đặt một dấu chấm dừng cho thực thi của hàm đó và chờ cho một Promise được trả về từ một biểu thức. Nếu Promise được giải quyết thành công, giá trị của nó sẽ được trả về. Nếu Promise bị từ chối (rejected), một ngoại lệ sẽ được ném và việc thực thi của hàm sẽ dừng lại.

Example
```
async function myFunction() {
    return Promise.reject(new Error("Đã xảy ra lỗi trong asyncFunctionWithError"))
  };
 

async function Fetchdata(){
try {
    let response = await myFunction() ;
    console.log(response)
}catch (error) {

    console.log(error.message)
}

}

Fetchdata()

output: Đã xảy ra lỗi trong asyncFunctionWithError  

```
## Arrow Function
 là cú pháp viết hàm  ngắn hơn và dễ hiểu hơn trong ES6 
```
syntax : 
 let variable = (parameter) => { 
    //code body
 }

 //call: variable() 



```

* arrow function không có context() , với các function khác thì context() của hàm chính là đối tượng gọi hàm ( nếu thông qua 1 đối tượng thì chính là obj ) , nếu không thông qua thì this là window ( global)
 Arrow function không có context riêng của nó, nó sẽ sử dụng context của hàm gần nhất. Context của arrow function được xác định tại thời điểm khai báo, không thay đổi sau này.*
 ```
 function dosomething(){
   console.log(this)
 }
 //this => window
 const obj = {
    name: "John",
    greet: function() {
        const innerFunction = () => {
            console.log("Hello, " + this.name);
        };
        innerFunction();
    }
};
//this=>  obj
obj.greet();
 ```